export default {
    SET_ALL_SCHOOL: "SET_ALL_SCHOOL",
    FETCH_USER_FAVORITE: "FETCH_USER_FAVORITE",
    FETCH_USER_FAVORITE_SUCCESS: "FETCH_USER_FAVORITE_SUCCESS",
    FETCH_USER_FAVORITE_FAIL: "FETCH_USER_FAVORITE_SUCCESS",
    ADD_USER_FAVORITE: "ADD_USER_FAVORITE",
    UPDATE_USER_FAVORITE: "UPDATE_USER_FAVORITE",
    DELETE_USER_FAVORITE: "DELETE_USER_FAVORITE",

    SET_USER_DATA: "SET_USER_DATA",
    REMOVE_USER_DATA: "REMOVE_USER_DATA",

    // GET_FRIEND_SUGGEST_VIA_LOCATION: "GET_FRIEND_SUGGEST_VIA_LOCATION",
    // GET_FRIEND_SUGGEST_VIA_FAVORITE: "GET_FRIEND_SUGGEST_VIA_FAVORITE",
    // GET_FRIEND_SUGGEST_VIA_LOCATION_SUCCESS: "GET_FRIEND_SUGGEST_VIA_LOCATION_SUCCESS",
    // GET_FRIEND_SUGGEST_VIA_FAVORITE_SUCCESS: "GET_FRIEND_SUGGEST_VIA_FAVORITE_SUCCESS",
    SET_FRIEND_SUGGEST: "SET_FRIEND_SUGGEST",
    SET_FRIEND_LOCATION: "SET_FRIEND_LOCATION",
    REMOVE_FRIEND_SUGGEST: "REMOVE_FRIEND_SUGGEST",
    REMOVE_FRIEND_LOCATION: "REMOVE_FRIEND_LOCATION",

    FETCH_ALL_MAJOR_LIST: "FETCH_ALL_MAJOR_LIST",

    SET_SUGGEST_GROUP: "SET_SUGGEST_GROUP",
    REMOVE_SUGGEST_GROUP: "SET_SUGGEST_GROUP",

    SET_SELECTED_FRIEND: "SET_SELECTED_FRIEND",
    REMOVE_SELECTED_FRIEND: "REMOVE_SELECTED_FRIEND",

    SET_GROUP_MESSAGE: "SET_GROUP_MESSAGE",
    SET_MESSAGE_USER: "SET_PERSON_MESSAGE_USER",
    ADD_MESSAGE_TO_GROUP: "ADD_MESSAGE_TO_GROUP",
    ADD_MESSAGE_TO_USER: "ADD_MESSAGE_TO_USER"
}