require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Groomate' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-location', :path => '../node_modules/react-native-location'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'GroomateTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '-DDONT_AUTOINSTALL_REANIMATED'
        end
    end
  end
end

target 'Groomate-tvOS' do
  # Pods for Groomate-tvOS

  target 'Groomate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
